[package]
name = "proj_fix"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytes = "1.10.1"
chrono = "0.4.41"
dashmap = "6.1.0"
memchr = "2.7.5"
smallvec = "1.15.1"
tokio = {version = "1.47.0", features = ["full"]}
log = "0.4.27"
fast_log = "1.7.7"
