appenders:
  stdout:
    kind: console
    encoder:
      # Timestamp with nanosecond precision:
      #   %Y year, %m month, %d day
      #   %H hour, %M minute, %S second
      #   %.f fractional seconds (up to nanoseconds)
      # {d(...)}   → formatted date/time
      # {l}        → log level (e.g. INFO, ERROR)
      # {m}        → the log message
      # {n}        → newline
      pattern: '{d(%Y-%m-%dT%H:%M:%S%.9f)} [{l}] {m}{n}'
  logfile:
    kind: file
    path: "app.log"
    encoder:
      # Same pattern for the file appender
      pattern: '{d(%Y-%m-%dT%H:%M:%S%.9f)} [{l}] {m}{n}'

root:
  # Minimum level for messages to be logged (trace, debug, info, warn, error)
  level: info
  appenders:
    - stdout   # send to console
    - logfile  # also send to app.log
